name: python-tests

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]          # keep your target runtime
    steps:
      - uses: actions/checkout@v4

      - name: Set-up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt      # <-- your bot’s deps

      - name: Install test-only deps
        # dpytest *is* the package you want; it exposes the
        #   module name `discord.ext.test`
        run: |
          pip install \
              pytest            \
              pytest-asyncio     \
              dpytest            \
              tinydb

      - name: Run tests
        run: pytest -v
