# .github/workflows/python-tests.yml
name: python-tests

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set-up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      # ───── install test-only libraries ─────
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          # pytest and friends *with* deps
          pip install pytest pytest-asyncio tinydb
          # dpytest alone, but skip its deps (discord.py)
          pip install dpytest --no-deps

      # ───── install runtime libraries (Py-Cord et al.) ─────
      - name: Install runtime dependencies
        run: |
          pip install -r requirements.txt     # grabs py-cord 2.6.1 and friends

      - name: Run test-suite
        run: pytest -v
