name: python-tests

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4

    - name: Set-up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    - name: Install runtime + dev deps
      run: |
        python -m pip install --upgrade pip
        # runtime
        pip install -r requirements.txt
        # tiny helpers for the suite
        pip install pytest pytest-asyncio \
                    discord-ext-test \
                    tinydb
        # ← discord-ext-test is the dpytest / testcord distribution

    - name: Run tests
      run: pytest -v
