name: Python tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: "dummy"           # the bot never logs in during tests
      GOOGLE_SHEET_URL: ""             # disables remote fetch
    strategy:
      matrix:
        python-version: [ "3.13" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dev / test deps
        run: pip install -r requirements-dev.txt

      - name: Run pytest
        run: pytest -v
